$(document).ready(function(){
  $(".clickable1").click(function(){
    $("#snakes").toggle();
  })
  $(".clickable2").click(function(){
    $("#whales").toggle();
  })
  $(".clickable3").click(function(){
    $("#bats").toggle();
  })
});
